os: linux
dist: trusty
language: generic
sudo: required
branches:
  only:
  - "/^develop\\/.*$/"
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - DOCKER_IMAGE_NAME=jpfanappapi:1.0.0
git:
  submodules: false
stages:
- name: develop
  if: branch =~ ^develop/.*$
jobs:
  include:
  - stage: develop
    name: Develop Job
    before_install:
    - openssl aes-256-cbc -K $encrypted_efbae0515365_key -iv $encrypted_efbae0515365_iv -in .prod.env.enc -out .prod.env -d
    script:
    - docker build -f Dockerfile --build-arg env=production -t $DOCKER_IMAGE_NAME .